from selenium.webdriver.common.by import By

class UrbanRoutesLocators:
    from_field = (By.ID, 'from')
    to_field = (By.ID, 'to')
    button_order_taxi = (By.CSS_SELECTOR, '.button.round')
    text_comfort_tariff = (By.TAG_NAME, 'Comfort')
    comfort_tariff_button =(By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[1]/div[5]')
    button_phone_number = (By.CLASS_NAME, 'np-text')
    text_popup= (By.XPATH, '//*[@id="root"]/div/div[1]/div[2]/div[1]/div')
    enter_phone_number =(By.ID, 'phone')
    button_next=(By.XPATH, '//button[@class="button full"]')
    text_next = (By.XPATH, '//*[@id="root"]/div/div[1]/div[2]/div[2]/div')
    enter_code= (By.ID, 'code')
    button_confirm= (By.XPATH, '//*[text()="Confirmar"]')
    validate_confirm = (By.CLASS_NAME, 'np-button filled')
    button_payment_method = (By.CLASS_NAME, 'pp-text')
    text_payment = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/div[1]')
    button_add_card=(By.CLASS_NAME, 'pp-plus-container')
    text_add_card = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[2]/div')
    set_credit_card = (By.CLASS_NAME, 'card-number-input')
    card_number= (By.XPATH, '//*[@id="number"]')
    code_number= (By.XPATH,'//div[@class="card-code-input"]/input[@id="code"]')
    agree_card = (By.XPATH, '//*[text()="Agregar"]')
    validate_agree = (By.XPATH, '//input[@id="card-1"]')
    close_button = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/button')
    validate_text_card = (By.XPATH, '//div[@class="pp-value-text"]')
    driver_message_input = (By.XPATH, '//*[@id="comment"]')
    input_comment = (By.CSS_SELECTOR, "#comment")
    prueba=(By.CLASS_NAME, "slider")
    select_blanket_handkerchiefs = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/span')
    validate_blanket_handkerchiefs = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/input')
    order_ice_cream = (By.CLASS_NAME, 'counter-plus')
    count_ice_cream=(By.XPATH,'//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[2]')
    button_order_a_taxi =(By.CLASS_NAME, 'smart-button-main')
    validate_modal_taxi = (By.CLASS_NAME, 'order-header-title')
